config/routes.rb
Rails.application.routes.draw do


  resources :phones
  devise_for :users
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true




end

app/models/phone.rb
class Phone < ApplicationRecord
  belongs_to :user

  def self.check_phone_number(phone_number)
    phone = Phone.where({phone_number: phone_number})
    if phone.empty?
      true
    else
      false
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include ApplicationHelper

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/phones_controller.rb
class PhonesController < ApplicationController
  before_action :set_phone, only: [:show, :edit, :update, :destroy]

  # GET /phones
  # GET /phones.json
  def index
    @phones = Phone.all
  end

  # GET /phones/1
  # GET /phones/1.json
  def show
  end

  # GET /phones/new
  def new
    @phone = Phone.new
  end

  # GET /phones/1/edit
  def edit
  end

  # POST /phones
  # POST /phones.json
  def create
    phone_number = nil
    unless phone_params[:phone_number]
      loop do
        phone_number = "#{rand(111...999)}#{rand(111...999)}#{rand(1111...9999)}"
        break if Phone.check_phone_number(phone_number)
      end
      phone_params[:phone_number] = phone_number
    end

    if phone_params[:phone_number].to_s.length.eql? 10
      @phone = Phone.new(phone_params)
    end

    respond_to do |format|
      if @phone.save
        format.html {redirect_to @phone, notice: 'Phone was successfully created.'}
        format.json {render :show, status: :created, location: @phone}
      else
        format.html {render :new}
        format.json {render json: @phone.errors, status: :unprocessable_entity}
      end
    end
  end

  # PATCH/PUT /phones/1
  # PATCH/PUT /phones/1.json
  def update
    respond_to do |format|
      if @phone.update(phone_params)
        format.html {redirect_to @phone, notice: 'Phone was successfully updated.'}
        format.json {render :show, status: :ok, location: @phone}
      else
        format.html {render :edit}
        format.json {render json: @phone.errors, status: :unprocessable_entity}
      end
    end
  end

  # DELETE /phones/1
  # DELETE /phones/1.json
  def destroy
    @phone.destroy
    respond_to do |format|
      format.html {redirect_to phones_url, notice: 'Phone was successfully destroyed.'}
      format.json {head :no_content}
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_phone
    @phone = Phone.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def phone_params
    params.fetch(:phone, {})
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/phones_helper.rb
module PhonesHelper
end

app/views/home/index.html.erb
<div class="top-menu row centered-form center-block">
  <div class="container col-md-offset-1">
  </div>
</div>

<div class="list">
  <dl>
    OLÁ
  </dl>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EngineerAiTest</title>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<div class="d-flex flex-column flex-md-row align-items-center p-1 px-md-4 mb-3 bg-white border-bottom shadow-sm">
  <%= link_to 'EngineerAiTest', root_path, class: "navbar-brand" %>

  <% if signed_in? %>
    <span class="m-2"><%= current_user.email %></span>
    <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "m-2 btn btn-success" %>
  <% else %>
    <%= link_to "Sign in", user_session_path, class: "m-2 btn btn-success" %>
    <%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary" %>
  <% end %>
</div>

<div class="container">
  <%= yield %>
</div>
</body>
</html>

app/views/phones/_form.html.erb
<%= form_with(model: phone, local: true) do |form| %>
  <% if phone.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(phone.errors.count, "error") %> prohibited this phone from being saved:</h2>

      <ul>
      <% phone.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: :phone_user_id %>
  </div>

  <div class="field">
    <%= form.label :phone_number %>
    <%= form.text_field :phone_number, id: :phone_phone_number %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/phones/edit.html.erb
<h1>Editing Phone</h1>

<%= render 'form', phone: @phone %>

<%= link_to 'Show', @phone %> |
<%= link_to 'Back', phones_path %>

app/views/phones/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Phones</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Phone number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @phones.each do |phone| %>
      <tr>
        <td><%= phone.user %></td>
        <td><%= phone.phone_number %></td>
        <td><%= link_to 'Show', phone %></td>
        <td><%= link_to 'Edit', edit_phone_path(phone) %></td>
        <td><%= link_to 'Destroy', phone, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Phone', new_phone_path %>

app/views/phones/new.html.erb
<h1>New Phone</h1>

<%= render 'form', phone: @phone %>

<%= link_to 'Back', phones_path %>

app/views/phones/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @phone.user %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @phone.phone_number %>
</p>

<%= link_to 'Edit', edit_phone_path(@phone) %> |
<%= link_to 'Back', phones_path %>